### ISSUE TITLE
Crash miner

### ISSUE THREAD

**Issue by kellixon** [Zaexides/SteamWorld#21]
MC 1.12.2. Forge 14.23.5.2775. SteamWorld 0.4.0.1
CrashReport - https://pastebin.com/GFftwxSU
---------------------------------------------------------
Time: 2018-11-23 12:37:42 MSK
Description: Ticking block entity

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.util.NonNullList.get(SourceFile:44)
    at zaexides.steamworld.recipe.handling.MinerRecipeHandler.GetRandomResult(MinerRecipeHandler.java:40)
    at zaexides.steamworld.te.TileEntityMiner.Execute(TileEntityMiner.java:139)
    at zaexides.steamworld.te.TileEntityMiner.update(TileEntityMiner.java:107)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbl000(World.java:5131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

-----------------------------
15 minute later
------------------------------
Time: 2018-11-23 12:53:16 MSK
Description: Ticking block entity

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.util.NonNullList.get(SourceFile:44)
    at zaexides.steamworld.recipe.handling.MinerRecipeHandler.GetRandomResult(MinerRecipeHandler.java:40)
    at zaexides.steamworld.te.TileEntityMiner.Execute(TileEntityMiner.java:139)
    at zaexides.steamworld.te.TileEntityMiner.update(TileEntityMiner.java:107)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbl000(World.java:5131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by Zaexides** [comment]
Thanks for reporting this, can you upload the mod config?

**Comment by kellixon** [comment]
All default. Clear folder minecraft config.

**Comment by Zaexides** [comment]
Alright, a fix has been made. Update hopefully today/this weekend.
Once again, thank you very much for reporting this

**Comment by Zaexides** [comment]
I should probably also have mentioned that in the meanwhile, you can edit the config and remove all the entries that start with "od:" that don't sound like ores that are in your game (e.g. oreArdite and oreCobalt are from Tinkers' Construct)
